
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankApi
    username: postgres
    password: 67551951
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cashplus
          jwk-set-uri: http://localhost:8080/realms/cashplus/protocol/openid-connect/certs


server:
  port: '8081'
  servlet:
    context-path: /api
